In [42]:
import pandas as pd
import bcrypt

In [43]:
prof_data = pd.read_csv("Professors.csv")
student_data = pd.read_csv("Students_TA.csv")

student_data

,Full Name,Email,Age,Zip,Phone,Gender,City,State,Password,Street,...,Course 3 Details,Course 3 Section,Course 3 Section Limit,Course 3 HW_No,Course 3 HW_Details,Course 3 HW_Grade,Course 3 EXAM_No,Course 3 Exam_Details,Course 3 EXAM_Grade,Teaching Team ID
0,Alisa Lynch,ally47@nittany.edu,19,62901,1507045398,F,Carbondale,Illinois,ixg1libp,78 South Brewery Ave.,...,3 Credit Course.,2.0,60,1.0,Turn in this homework online!,90.0,NaN,NaN,NaN,NaN
1,Alisha Murray,almu46@nittany.edu,21,46376,3852017301,F,Schneider,Indiana,4eystjwe,639 Princeton Rd.,...,3 Credit Course.,1.0,70,1.0,Turn in this homework online!,60.0,1.0,Closed book exam for 100 marks,84.0,NaN
2,Alice Kiehn,alki89@nittany.edu,20,30529,4651079903,M,Commerce,Georgia,p0ulbn26,8985 Cambridge Ave.,...,3 Credit Course.,1.0,70,1.0,Turn in this homework online!,74.0,1.0,Closed book exam for 100 marks,87.0,NaN
3,Anastasia Shields,ansh34@nittany.edu,18,72571,1245720203,F,Rosie,Arkansas,06e84eor,55 Hall St.,...,3 Credit Course.,1.0,70,1.0,Turn in this homework online!,67.0,1.0,Closed book exam for 100 marks,95.0,NaN
4,Alyce Leuschke Jr.,alle64@nittany.edu,21,80104,5672573168,M,Castle Rock,Colorado,ev4n7hoh,232 W. Homewood Ave.,...,3 Credit Course.,2.0,60,1.0,Turn in this homework online!,97.0,1.0,Closed book exam for 100 marks,97.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Dr. Elton Green,drel69@nittany.edu,18,71851,8123631542,M,Mineral Springs,Arkansas,to578yi5,8985 Cambridge Ave.,...,3 Credit Course.,2.0,60,1.0,Turn in this homework online!,78.0,1.0,Closed book exam for 100 marks,70.0,NaN
996,Florian Mante,flma12@nittany.edu,22,92276,5317437262,F,Thousand Palms,California,52ibosdi,798 North Euclid Drive,...,3 Credit Course.,2.0,60,1.0,Turn in this homework online!,69.0,NaN,NaN,NaN,NaN
997,Frank Ryan,frry45@nittany.edu,19,46340,7122157384,F,Hanna,Indiana,hwazzxlh,461 Heather Street,...,3 Credit Course.,2.0,60,1.0,Turn in this homework online!,73.0,1.0,Closed book exam for 100 marks,68.0,NaN
998,Dr. Lambert Jaskolski,drla86@nittany.edu,18,81092,7719679541,M,Wiley,Colorado,jy0in5m2,358 Marvon Ave.,...,3 Credit Course.,1.0,70,1.0,Turn in this homework online!,81.0,1.0,Closed book exam for 100 marks,81.0,NaN
999,Darlene Flatley,dafl41@nittany.edu,22,50039,5429668226,M,Bouton,Iowa,fff7sx3o,9408 Anderson Court,...,3 Credit Course.,1.0,70,1.0,Turn in this homework online!,63.0,1.0,Closed book exam for 100 marks,77.0,NaN

In [44]:
prof_data
user_prof = prof_data[["Email", "Password"]]
user_stud = student_data[["Email", "Password"]]
user_data = pd.concat([user_prof, user_stud])
user_data[user_data["Email"] == "dm17@nittany.edu"]
user_data.to_csv("users_not_encrypted.csv", index = False)

In [29]:
lst = list(user_data["Password"])
for i in range(len(user_data["Password"])):
    user_data["Password"][i] = bcrypt.hashpw(lst[i].encode('utf8'), bcrypt.gensalt(rounds = 10, prefix=b"2a"))

In [30]:
print(user_data[user_data["Email"] == "dm17@nittany.edu"])
# user_data.to_csv("users.csv", index = False)

               Email                                           Password
53  dm17@nittany.edu  b'$2a$10$B0fq4PEJMWokGpIHuu07quhbOmA6xaiFglINS...

In [41]:
bcrypt.hashpw("jlt1x825".encode('utf8'), bcrypt.gensalt(rounds = 10, prefix=b"2a"))

b'$2a$10$3G.7rfYPnaQx9/L.iIb/r.UacQ0cMJxXRmzJCC19Cm.50qMa.baU6'